package complexity_test

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/yanmxa/metron/internal/axis"
	"github.com/yanmxa/metron/internal/axis/complexity"
	"github.com/yanmxa/metron/internal/target"
)

// repo builds a throwaway git repository, commits base, then applies head.
// It returns the root. Everything the axis does — resolving a diff, reading the
// base revision, matching functions across it — needs real git.
func repo(t *testing.T, base, head map[string]string) string {
	t.Helper()
	if _, err := exec.LookPath("git"); err != nil {
		t.Skip("git not available")
	}
	dir := t.TempDir()

	write := func(files map[string]string) {
		for name, body := range files {
			p := filepath.Join(dir, name)
			if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
				t.Fatal(err)
			}
		}
	}
	run := func(args ...string) {
		cmd := exec.Command("git", args...)
		cmd.Dir = dir
		if out, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("git %s: %v\n%s", strings.Join(args, " "), err, out)
		}
	}

	base["go.mod"] = "module example.com/m\n\ngo 1.26\n"
	write(base)
	run("init", "-q", "-b", "main")
	run("config", "user.email", "t@example.com")
	run("config", "user.name", "t")
	run("add", "-A")
	run("commit", "-qm", "base")

	write(head)
	return dir
}

func run(t *testing.T, dir string, cfg complexity.Config) *axis.Result {
	t.Helper()
	tgt, err := target.Resolve(context.Background(), dir, "main")
	if err != nil {
		t.Fatal(err)
	}
	res, err := complexity.New(cfg).Run(context.Background(), tgt, nil)
	if err != nil {
		t.Fatal(err)
	}
	return res
}

func measure(t *testing.T, r *axis.Result, key string) axis.Measure {
	t.Helper()
	for _, m := range r.Measures {
		if m.Key == key {
			return m
		}
	}
	t.Fatalf("no measure %q in %+v", key, r.Measures)
	return axis.Measure{}
}

func TestDeltaCatchesAFunctionThatGotWorse(t *testing.T) {
	// The reading this axis exists for. The absolute value stays inside its
	// range here, so only the delta can catch the change.
	dir := repo(t,
		map[string]string{"a.go": `package a

func Check(n int) bool {
	if n > 0 {
		return true
	}
	return false
}
`},
		map[string]string{"a.go": `package a

func Check(n int) bool {
	if n > 0 {
		if n > 10 {
			if n > 100 {
				return true
			}
		}
		return true
	}
	return false
}
`})

	r := run(t, dir, complexity.DefaultConfig())

	delta := measure(t, r, "complexity.delta_max")
	if delta.Value <= 0 {
		t.Errorf("delta = %v, want positive — the function gained nesting", delta.Value)
	}
	if delta.Status != axis.StatusFail {
		t.Errorf("delta status = %v, want fail", delta.Status)
	}
	if cog := measure(t, r, "complexity.cognitive_max"); cog.Status == axis.StatusFail {
		t.Error("this fixture is only interesting while the absolute value still passes")
	}
	if delta.Note != "Check" {
		t.Errorf("the reading should name the function, got %q", delta.Note)
	}
}

func TestANewFunctionHasNoDelta(t *testing.T) {
	// There is nothing for it to have got worse against.
	dir := repo(t,
		map[string]string{"a.go": "package a\n"},
		map[string]string{"a.go": `package a

func Added(n int) bool {
	if n > 0 {
		return true
	}
	return false
}
`})
	r := run(t, dir, complexity.DefaultConfig())
	if d := measure(t, r, "complexity.delta_max"); d.Value != 0 {
		t.Errorf("delta = %v, want 0 for a new function", d.Value)
	}
}

func TestGeneratedFilesAreNotGraded(t *testing.T) {
	// Mutating or grading generated code measures the generator.
	dir := repo(t,
		map[string]string{"a.go": "package a\n"},
		map[string]string{"a.go": `// Code generated by protoc-gen-go. DO NOT EDIT.

package a

func Deep(a, b, c, d bool) int {
	if a {
		if b {
			if c {
				if d {
					return 1
				}
			}
		}
	}
	return 0
}
`})
	r := run(t, dir, complexity.DefaultConfig())
	if m := measure(t, r, "complexity.cognitive_max"); m.Status != axis.StatusUnmeasured {
		t.Errorf("a generated file should leave nothing to measure, got %+v", m)
	}
}

func TestTestFilesAreNotGraded(t *testing.T) {
	dir := repo(t,
		map[string]string{"a.go": "package a\n"},
		map[string]string{"a_test.go": `package a

import "testing"

func TestDeep(t *testing.T) {
	for i := 0; i < 3; i++ {
		if i > 0 {
			if i > 1 {
				t.Log(i)
			}
		}
	}
}
`})
	r := run(t, dir, complexity.DefaultConfig())
	if m := measure(t, r, "complexity.cognitive_max"); m.Status != axis.StatusUnmeasured {
		t.Errorf("test complexity is a different question, got %+v", m)
	}
}

func TestConfiguredLimitIsHonoured(t *testing.T) {
	dir := repo(t,
		map[string]string{"a.go": "package a\n"},
		map[string]string{"a.go": `package a

func F(a, b bool) int {
	if a {
		if b {
			return 1
		}
	}
	return 0
}
`})
	cfg := complexity.DefaultConfig()
	cfg.MaxCognitive = 1
	if m := measure(t, run(t, dir, cfg), "complexity.cognitive_max"); m.Status != axis.StatusFail {
		t.Errorf("a limit of 1 should fail, got %+v", m)
	}

	cfg.MaxCognitive = 100
	if m := measure(t, run(t, dir, cfg), "complexity.cognitive_max"); m.Status != axis.StatusOK {
		t.Errorf("a limit of 100 should pass, got %+v", m)
	}
}

func TestPerFunctionDataIsExposedForCombining(t *testing.T) {
	// CRAP needs cyclomatic from here and mutants from the mutation axis.
	dir := repo(t,
		map[string]string{"a.go": "package a\n"},
		map[string]string{"a.go": "package a\n\nfunc F(n int) int {\n\tif n > 0 {\n\t\treturn 1\n\t}\n\treturn 0\n}\n"})
	r := run(t, dir, complexity.DefaultConfig())
	if len(r.Funcs) == 0 {
		t.Fatal("no per-function records")
	}
	f := r.Funcs[0]
	if f.Function != "F" || f.Cyclomatic == 0 || f.Path != "a.go" {
		t.Errorf("incomplete record: %+v", f)
	}
}
